//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoSalud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERGOS_Cuestionarios_Resultados_N01
    {
        public int id_Cuestionario_Resultado { get; set; }
        public Nullable<int> id_cuestionario_trabajador { get; set; }
        public Nullable<int> id_respuesta { get; set; }
        public Nullable<int> id_pregunta { get; set; }
        public Nullable<int> id_encuesta { get; set; }
        public Nullable<int> Calificacion { get; set; }
    
        public virtual ERGOS_Cuestionarios_Trabajador_N01 ERGOS_Cuestionarios_Trabajador_N01 { get; set; }
        public virtual ERGOS_Preguntas_N01 ERGOS_Preguntas_N01 { get; set; }
        public virtual ERGOS_Respuestas_N01 ERGOS_Respuestas_N01 { get; set; }
    }
}
