//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoSalud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERGOS_Empresas_N01
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ERGOS_Empresas_N01()
        {
            this.ERGOS_Centros_Trabajo_N01 = new HashSet<ERGOS_Centros_Trabajo_N01>();
            this.ERGOS_Cuestionarios_Trabajador_N01 = new HashSet<ERGOS_Cuestionarios_Trabajador_N01>();
            this.ERGOS_Departamentos_N01 = new HashSet<ERGOS_Departamentos_N01>();
            this.ERGOS_Guia_Observacion_N01 = new HashSet<ERGOS_Guia_Observacion_N01>();
        }
    
        public int id_empresa { get; set; }
        public string Razon_Social { get; set; }
        public string Telefono { get; set; }
        public string Contacto_Nombre { get; set; }
        public string Email { get; set; }
        public int id_encuesta { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string RFC { get; set; }
        public string Domicilio { get; set; }
        public string Actividad_Principal { get; set; }
        public string Nombre_Empresa { get; set; }
        public string Centro_Trabajo { get; set; }
        public string Cedula_Profesional { get; set; }
        public Nullable<System.DateTime> Fecha_Auditoria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERGOS_Centros_Trabajo_N01> ERGOS_Centros_Trabajo_N01 { get; set; }
        public virtual ERGOS_Cuestionarios_N01 ERGOS_Cuestionarios_N01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERGOS_Cuestionarios_Trabajador_N01> ERGOS_Cuestionarios_Trabajador_N01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERGOS_Departamentos_N01> ERGOS_Departamentos_N01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERGOS_Guia_Observacion_N01> ERGOS_Guia_Observacion_N01 { get; set; }
    }
}
