//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoSalud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERGOS_Guia_Observacion_N01
    {
        public int id_guia { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<int> id_pregunta { get; set; }
        public Nullable<int> Calificacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> id_centro_trabajo { get; set; }
        public string Comentarios { get; set; }
    
        public virtual ERGOS_Empresas_N01 ERGOS_Empresas_N01 { get; set; }
        public virtual ERGOS_Guia_Preguntas_N01 ERGOS_Guia_Preguntas_N01 { get; set; }
    }
}
