//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoSalud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERGOS_Cuestionarios_Trabajador_N01
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ERGOS_Cuestionarios_Trabajador_N01()
        {
            this.ERGOS_Cuestionarios_Resultados_N01 = new HashSet<ERGOS_Cuestionarios_Resultados_N01>();
        }
    
        public int id_cuestionario_trabajador { get; set; }
        public int id_trabajador { get; set; }
        public Nullable<int> id_encuesta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Estado_Civil { get; set; }
        public string Nivel_Esudios { get; set; }
        public string Ocupacion { get; set; }
        public Nullable<int> Departamento { get; set; }
        public string Tipo_puesto { get; set; }
        public string Tipo_Contratacion { get; set; }
        public string Tipo_Jornada { get; set; }
        public string Rotacion_Turno { get; set; }
        public Nullable<int> Experiencia_puesto_actual { get; set; }
        public Nullable<int> Experiencia_puesto_laboral { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public Nullable<int> Tipo_Personal { get; set; }
        public Nullable<int> id_centro_trabajo { get; set; }
    
        public virtual ERGOS_Centros_Trabajo_N01 ERGOS_Centros_Trabajo_N01 { get; set; }
        public virtual ERGOS_Cuestionarios_N01 ERGOS_Cuestionarios_N01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ERGOS_Cuestionarios_Resultados_N01> ERGOS_Cuestionarios_Resultados_N01 { get; set; }
        public virtual ERGOS_Empresas_N01 ERGOS_Empresas_N01 { get; set; }
        public virtual ERGOS_Departamentos_N01 ERGOS_Departamentos_N01 { get; set; }
    }
}
