//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoSalud.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CastSoft_LETConsultingEntities : DbContext
    {
        public CastSoft_LETConsultingEntities()
            : base("name=CastSoft_LETConsultingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ERGOS_Centros_Trabajo_N01> ERGOS_Centros_Trabajo_N01 { get; set; }
        public virtual DbSet<ERGOS_Cuestionarios_N01> ERGOS_Cuestionarios_N01 { get; set; }
        public virtual DbSet<ERGOS_Cuestionarios_Resultados_N01> ERGOS_Cuestionarios_Resultados_N01 { get; set; }
        public virtual DbSet<ERGOS_Cuestionarios_Trabajador_N01> ERGOS_Cuestionarios_Trabajador_N01 { get; set; }
        public virtual DbSet<ERGOS_Departamentos_N01> ERGOS_Departamentos_N01 { get; set; }
        public virtual DbSet<ERGOS_Empresas_N01> ERGOS_Empresas_N01 { get; set; }
        public virtual DbSet<ERGOS_Guia_Observacion_N01> ERGOS_Guia_Observacion_N01 { get; set; }
        public virtual DbSet<ERGOS_Guia_Preguntas_N01> ERGOS_Guia_Preguntas_N01 { get; set; }
        public virtual DbSet<ERGOS_Preguntas_N01> ERGOS_Preguntas_N01 { get; set; }
        public virtual DbSet<ERGOS_Preguntas_S2_N02> ERGOS_Preguntas_S2_N02 { get; set; }
        public virtual DbSet<ERGOS_Respuestas_N01> ERGOS_Respuestas_N01 { get; set; }
        public virtual DbSet<VW_ERGOS_Results_V01> VW_ERGOS_Results_V01 { get; set; }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Categorias_1_E2_Resultados_Pilot")]
        public virtual IQueryable<fnDemo_N035_Categorias_1_E2_Resultados_Pilot_Result> fnDemo_N035_Categorias_1_E2_Resultados_Pilot(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Categorias_1_E2_Resultados_Pilot_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Categorias_1_E2_Resultados_Pilot](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Categorias_1_Resultados_Pilot")]
        public virtual IQueryable<fnDemo_N035_Categorias_1_Resultados_Pilot_Result> fnDemo_N035_Categorias_1_Resultados_Pilot(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Categorias_1_Resultados_Pilot_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Categorias_1_Resultados_Pilot](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Categorias_2_E2_Resultados_Pilot")]
        public virtual IQueryable<fnDemo_N035_Categorias_2_E2_Resultados_Pilot_Result> fnDemo_N035_Categorias_2_E2_Resultados_Pilot(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Categorias_2_E2_Resultados_Pilot_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Categorias_2_E2_Resultados_Pilot](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Categorias_2_Resultados_Pilot")]
        public virtual IQueryable<fnDemo_N035_Categorias_2_Resultados_Pilot_Result> fnDemo_N035_Categorias_2_Resultados_Pilot(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Categorias_2_Resultados_Pilot_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Categorias_2_Resultados_Pilot](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Categorias_3_E2_Resultados_Pilot")]
        public virtual IQueryable<fnDemo_N035_Categorias_3_E2_Resultados_Pilot_Result> fnDemo_N035_Categorias_3_E2_Resultados_Pilot(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Categorias_3_E2_Resultados_Pilot_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Categorias_3_E2_Resultados_Pilot](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Categorias_3_Resultados_Pilot")]
        public virtual IQueryable<fnDemo_N035_Categorias_3_Resultados_Pilot_Result> fnDemo_N035_Categorias_3_Resultados_Pilot(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Categorias_3_Resultados_Pilot_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Categorias_3_Resultados_Pilot](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Categorias_4_E2_Resultados_Pilot")]
        public virtual IQueryable<fnDemo_N035_Categorias_4_E2_Resultados_Pilot_Result> fnDemo_N035_Categorias_4_E2_Resultados_Pilot(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Categorias_4_E2_Resultados_Pilot_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Categorias_4_E2_Resultados_Pilot](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Categorias_4_Resultados_Pilot")]
        public virtual IQueryable<fnDemo_N035_Categorias_4_Resultados_Pilot_Result> fnDemo_N035_Categorias_4_Resultados_Pilot(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Categorias_4_Resultados_Pilot_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Categorias_4_Resultados_Pilot](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Categorias_5_Resultados_Pilot")]
        public virtual IQueryable<fnDemo_N035_Categorias_5_Resultados_Pilot_Result> fnDemo_N035_Categorias_5_Resultados_Pilot(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Categorias_5_Resultados_Pilot_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Categorias_5_Resultados_Pilot](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Categorias_Pilot")]
        public virtual IQueryable<fnDemo_N035_Categorias_Pilot_Result> fnDemo_N035_Categorias_Pilot(Nullable<int> id_CT)
        {
            var id_CTParameter = id_CT.HasValue ?
                new ObjectParameter("id_CT", id_CT) :
                new ObjectParameter("id_CT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Categorias_Pilot_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Categorias_Pilot](@id_CT)", id_CTParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Categorias_Resultados_Pilot")]
        public virtual IQueryable<fnDemo_N035_Categorias_Resultados_Pilot_Result> fnDemo_N035_Categorias_Resultados_Pilot(Nullable<int> id_cliente, Nullable<int> id_encuesta)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            var id_encuestaParameter = id_encuesta.HasValue ?
                new ObjectParameter("id_encuesta", id_encuesta) :
                new ObjectParameter("id_encuesta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Categorias_Resultados_Pilot_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Categorias_Resultados_Pilot](@id_cliente, @id_encuesta)", id_clienteParameter, id_encuestaParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Dominios_1_E2_Resultados")]
        public virtual IQueryable<fnDemo_N035_Dominios_1_E2_Resultados_Result> fnDemo_N035_Dominios_1_E2_Resultados(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Dominios_1_E2_Resultados_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Dominios_1_E2_Resultados](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Dominios_1_Resultados")]
        public virtual IQueryable<fnDemo_N035_Dominios_1_Resultados_Result> fnDemo_N035_Dominios_1_Resultados(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Dominios_1_Resultados_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Dominios_1_Resultados](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Dominios_10_Resultados")]
        public virtual IQueryable<fnDemo_N035_Dominios_10_Resultados_Result> fnDemo_N035_Dominios_10_Resultados(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Dominios_10_Resultados_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Dominios_10_Resultados](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Dominios_2_E2_Resultados")]
        public virtual IQueryable<fnDemo_N035_Dominios_2_E2_Resultados_Result> fnDemo_N035_Dominios_2_E2_Resultados(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Dominios_2_E2_Resultados_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Dominios_2_E2_Resultados](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Dominios_2_Resultados")]
        public virtual IQueryable<fnDemo_N035_Dominios_2_Resultados_Result> fnDemo_N035_Dominios_2_Resultados(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Dominios_2_Resultados_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Dominios_2_Resultados](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Dominios_3_E2_Resultados")]
        public virtual IQueryable<fnDemo_N035_Dominios_3_E2_Resultados_Result> fnDemo_N035_Dominios_3_E2_Resultados(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Dominios_3_E2_Resultados_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Dominios_3_E2_Resultados](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Dominios_3_Resultados")]
        public virtual IQueryable<fnDemo_N035_Dominios_3_Resultados_Result> fnDemo_N035_Dominios_3_Resultados(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Dominios_3_Resultados_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Dominios_3_Resultados](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Dominios_4_E2_Resultados")]
        public virtual IQueryable<fnDemo_N035_Dominios_4_E2_Resultados_Result> fnDemo_N035_Dominios_4_E2_Resultados(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Dominios_4_E2_Resultados_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Dominios_4_E2_Resultados](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Dominios_4_Resultados")]
        public virtual IQueryable<fnDemo_N035_Dominios_4_Resultados_Result> fnDemo_N035_Dominios_4_Resultados(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Dominios_4_Resultados_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Dominios_4_Resultados](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Dominios_5_E2_Resultados")]
        public virtual IQueryable<fnDemo_N035_Dominios_5_E2_Resultados_Result> fnDemo_N035_Dominios_5_E2_Resultados(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Dominios_5_E2_Resultados_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Dominios_5_E2_Resultados](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Dominios_5_Resultados")]
        public virtual IQueryable<fnDemo_N035_Dominios_5_Resultados_Result> fnDemo_N035_Dominios_5_Resultados(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Dominios_5_Resultados_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Dominios_5_Resultados](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Dominios_6_E2_Resultados")]
        public virtual IQueryable<fnDemo_N035_Dominios_6_E2_Resultados_Result> fnDemo_N035_Dominios_6_E2_Resultados(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Dominios_6_E2_Resultados_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Dominios_6_E2_Resultados](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Dominios_6_Resultados")]
        public virtual IQueryable<fnDemo_N035_Dominios_6_Resultados_Result> fnDemo_N035_Dominios_6_Resultados(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Dominios_6_Resultados_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Dominios_6_Resultados](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Dominios_7_E2_Resultados")]
        public virtual IQueryable<fnDemo_N035_Dominios_7_E2_Resultados_Result> fnDemo_N035_Dominios_7_E2_Resultados(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Dominios_7_E2_Resultados_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Dominios_7_E2_Resultados](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Dominios_7_Resultados")]
        public virtual IQueryable<fnDemo_N035_Dominios_7_Resultados_Result> fnDemo_N035_Dominios_7_Resultados(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Dominios_7_Resultados_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Dominios_7_Resultados](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Dominios_8_E2_Resultados")]
        public virtual IQueryable<fnDemo_N035_Dominios_8_E2_Resultados_Result> fnDemo_N035_Dominios_8_E2_Resultados(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Dominios_8_E2_Resultados_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Dominios_8_E2_Resultados](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Dominios_8_Resultados")]
        public virtual IQueryable<fnDemo_N035_Dominios_8_Resultados_Result> fnDemo_N035_Dominios_8_Resultados(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Dominios_8_Resultados_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Dominios_8_Resultados](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Dominios_9_Resultados")]
        public virtual IQueryable<fnDemo_N035_Dominios_9_Resultados_Result> fnDemo_N035_Dominios_9_Resultados(Nullable<int> id_cliente)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Dominios_9_Resultados_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Dominios_9_Resultados](@id_cliente)", id_clienteParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fnDemo_N035_Grafica_Resultado_Preguntas")]
        public virtual IQueryable<fnDemo_N035_Grafica_Resultado_Preguntas_Result> fnDemo_N035_Grafica_Resultado_Preguntas(Nullable<int> id_encuesta, Nullable<int> id_empresa)
        {
            var id_encuestaParameter = id_encuesta.HasValue ?
                new ObjectParameter("id_encuesta", id_encuesta) :
                new ObjectParameter("id_encuesta", typeof(int));
    
            var id_empresaParameter = id_empresa.HasValue ?
                new ObjectParameter("id_empresa", id_empresa) :
                new ObjectParameter("id_empresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnDemo_N035_Grafica_Resultado_Preguntas_Result>("[CastSoft_LETConsultingEntities].[fnDemo_N035_Grafica_Resultado_Preguntas](@id_encuesta, @id_empresa)", id_encuestaParameter, id_empresaParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fn_Final_view_surveys")]
        public virtual IQueryable<fn_Final_view_surveys_Result> fn_Final_view_surveys(Nullable<int> id_CT)
        {
            var id_CTParameter = id_CT.HasValue ?
                new ObjectParameter("id_CT", id_CT) :
                new ObjectParameter("id_CT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_Final_view_surveys_Result>("[CastSoft_LETConsultingEntities].[fn_Final_view_surveys](@id_CT)", id_CTParameter);
        }
    
        [DbFunction("CastSoft_LETConsultingEntities", "fn_Final_view_surveys_S2")]
        public virtual IQueryable<fn_Final_view_surveys_S2_Result> fn_Final_view_surveys_S2(Nullable<int> id_CT)
        {
            var id_CTParameter = id_CT.HasValue ?
                new ObjectParameter("id_CT", id_CT) :
                new ObjectParameter("id_CT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_Final_view_surveys_S2_Result>("[CastSoft_LETConsultingEntities].[fn_Final_view_surveys_S2](@id_CT)", id_CTParameter);
        }
    
        public virtual int Answering_Guia(Nullable<int> id_guia, Nullable<int> respuesta)
        {
            var id_guiaParameter = id_guia.HasValue ?
                new ObjectParameter("id_guia", id_guia) :
                new ObjectParameter("id_guia", typeof(int));
    
            var respuestaParameter = respuesta.HasValue ?
                new ObjectParameter("Respuesta", respuesta) :
                new ObjectParameter("Respuesta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Answering_Guia", id_guiaParameter, respuestaParameter);
        }
    
        public virtual int Answering_Guia_Comentarios(Nullable<int> id_guia, string comentarios)
        {
            var id_guiaParameter = id_guia.HasValue ?
                new ObjectParameter("id_guia", id_guia) :
                new ObjectParameter("id_guia", typeof(int));
    
            var comentariosParameter = comentarios != null ?
                new ObjectParameter("Comentarios", comentarios) :
                new ObjectParameter("Comentarios", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Answering_Guia_Comentarios", id_guiaParameter, comentariosParameter);
        }
    
        public virtual int Answering_Survey(Nullable<int> id_CR, Nullable<int> respuesta)
        {
            var id_CRParameter = id_CR.HasValue ?
                new ObjectParameter("id_CR", id_CR) :
                new ObjectParameter("id_CR", typeof(int));
    
            var respuestaParameter = respuesta.HasValue ?
                new ObjectParameter("Respuesta", respuesta) :
                new ObjectParameter("Respuesta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Answering_Survey", id_CRParameter, respuestaParameter);
        }
    
        public virtual int Change_Status(string serial, string scanned_Place)
        {
            var serialParameter = serial != null ?
                new ObjectParameter("Serial", serial) :
                new ObjectParameter("Serial", typeof(string));
    
            var scanned_PlaceParameter = scanned_Place != null ?
                new ObjectParameter("Scanned_Place", scanned_Place) :
                new ObjectParameter("Scanned_Place", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Change_Status", serialParameter, scanned_PlaceParameter);
        }
    }
}
